services:
  postgresdb:
    image: postgres:alpine
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - db:/var/lib/postgres

  app:
    depends_on:
      - postgresdb
    image: ghcr.io/DraftShare/draftshare_backend:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT

volumes:
  db:
