services:
  postgresdb:
    image: postgres:alpine
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - /opt/app/db_data:/var/lib/postgresql/data

  app:
    depends_on:
      - postgresdb
    image: ghcr.io/draftshare/draftshare_backend:latest
    restart: unless-stopped
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRESDB_USER}:${POSTGRESDB_ROOT_PASSWORD}@postgresdb:${POSTGRESDB_DOCKER_PORT}/${POSTGRESDB_DATABASE}
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
